spring:
  profiles:
    active: local
    include: properties
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/photogram
    username: photogram
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP-POOL
      max-lifetime: 180000
      connection-timeout: 30000
  jpa:
    hibernate:
      connection:
        provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    properties:
      hibernate:
        default_schema: public
        show_sql: false
        format_sql: true
        use_sql: true
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
    main:
      allow-bean-definition-overriding: true

  security:
    user:
      name: parkpro
      password: amore

attachment:
  path: /Users/colin/Documents/File/upload/lulumedic/
